Controllers/FashionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopFashion.Data;
using ShopFashion.Models;

namespace ShopFashion.Controllers
{
    public class FashionsController : Controller
    {
        private readonly ShopFashionContext _context;

        public FashionsController(ShopFashionContext context)
        {
            _context = context;
        }

        // GET: Fashions
        public async Task<IActionResult> Index(string fashionGenre, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from b in _context.Fashion
                                            orderby b.LoaiHang
                                            select b.LoaiHang;
            var fashions = from b in _context.Fashion
                        select b;
            if (!string.IsNullOrEmpty(searchString))
            {
                fashions = fashions.Where(s => s.MatHang!.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(fashionGenre))
            {
                fashions = fashions.Where(x => x.LoaiHang == fashionGenre);
            }
            var fashionGenreVM = new FashionGenreViewModel
            {
                LoaiHangs = new SelectList(await
           genreQuery.Distinct().ToListAsync()),
                Fashions = await fashions.ToListAsync()
            };
            return View(fashionGenreVM);
        }
        public async Task<IActionResult> AdTrangChu(string fashionGenre, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from b in _context.Fashion
                                            orderby b.LoaiHang
                                            select b.LoaiHang;
            var fashions = from b in _context.Fashion
                           select b;
            if (!string.IsNullOrEmpty(searchString))
            {
                fashions = fashions.Where(s => s.MatHang!.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(fashionGenre))
            {
                fashions = fashions.Where(x => x.LoaiHang == fashionGenre);
            }
            var fashionGenreVM = new FashionGenreViewModel
            {
                LoaiHangs = new SelectList(await
           genreQuery.Distinct().ToListAsync()),
                Fashions = await fashions.ToListAsync()
            };
            return View(fashionGenreVM);
        }


        // GET: Fashions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fashion = await _context.Fashion
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fashion == null)
            {
                return NotFound();
            }

            return View(fashion);
        }

        // GET: Fashions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fashions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MatHang,NgayDatHang,NgayGiaoHang,LoaiHang,Gia")] Fashion fashion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fashion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fashion);
        }

        // GET: Fashions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fashion = await _context.Fashion.FindAsync(id);
            if (fashion == null)
            {
                return NotFound();
            }
            return View(fashion);
        }

        // POST: Fashions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MatHang,NgayDatHang,NgayGiaoHang,LoaiHang,Gia")] Fashion fashion)
        {
            if (id != fashion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fashion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FashionExists(fashion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fashion);
        }

        // GET: Fashions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fashion = await _context.Fashion
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fashion == null)
            {
                return NotFound();
            }

            return View(fashion);
        }

        // POST: Fashions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fashion = await _context.Fashion.FindAsync(id);
            _context.Fashion.Remove(fashion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FashionExists(int id)
        {
            return _context.Fashion.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopFashion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/ASP/site.css" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light nen  border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Fashions" asp-action="Index">ShopFashion</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Trang Chủ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Sản Phẩm Mới</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MuaXuan">Mùa Xuân</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MuaHa">Mùa Hạ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MuaThu">Mùa Thu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MuaDong">Mùa Đông </a>
                        </li>
                    </ul>
                </div>
                <form>
                     <input type="text" name="search" placeholder="Search..">
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ShopFashion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>